version: 2.1

jobs:
  build_ipa:
    macos:
      xcode: "15.4.0"

    environment:
      BUNDLE_PATH: vendor/bundle
      FL_OUTPUT_DIR: build
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8

    steps:
      - checkout

      - run:
          name: Setup environment
          command: |
            mkdir -p "$FL_OUTPUT_DIR"
            xcodebuild -version
            ruby -v
            git config --global user.email "ci@example.com"
            git config --global user.name "CI Bot"

      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
            - v1-bundle-

      - run:
          name: Install Bundler & Gems
          command: |
            gem install bundler -N
            bundle config set path vendor/bundle
            bundle install --jobs=4 --retry=3

      - save_cache:
          paths:
            - vendor/bundle
          key: v1-bundle-{{ checksum "Gemfile.lock" }}

      - run:
          name: Build IPA
          command: bundle exec fastlane release

      - store_artifacts:
          path: build

workflows:
  version: 2
  ios_ipa:
    jobs:
      - build_ipa:
          filters:
            branches:
              only:
                - main
